regions/municipalities/urls.py
from django.urls import path

from . import views

app_name = "municipalities"
urlpatterns = [
    path('', views.index, name='index'),
    path('municipality/<int:m_id>/', views.detail_municipalities, name='detail_municipalities'),
    path('region/<int:r_id>/', views.detail_regions, name='detail_regions'),
    path('add/municipality/', views.add_municipality, name='add_municipality'),
    path('municipality/edit/<int:m_id>', views.edit_municipality, name='edit_municipality'),
    path('municipality/delete/<int:m_id>', views.delete_municipality, name='delete_municipality'),
    path('region/edit/<int:r_id>', views.edit_region, name='edit_region'),
    path('region/delete/<int:r_id>', views.delete_region, name='delete_region'),
    path('add/region/', views.add_region, name='add_region')
]

regions/regions/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('municipalities/', include('municipalities.urls')),
    path('admin/', admin.site.urls)
]

regions/municipalities/models.py
from django.db import models

class Municipality(models.Model):
    STATE_OPTIONS = (
        ('A', 'Active'),
        ('U', 'Unactive')
    )
    code = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=150)
    state = models.CharField(max_length=1, choices=STATE_OPTIONS)

    def __str__(self):
        return self.name

class Region(models.Model):
    code = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=150)
    municipalities = models.ManyToManyField(Municipality, through='MunicipalityXRegion')

    def __str__(self):
        return self.name

class MunicipalityXRegion(models.Model):
    municipality = models.ForeignKey(Municipality, on_delete=models.CASCADE)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)

regions/municipalities/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .models import Region, Municipality, MunicipalityXRegion


def index(request):
    regions = Region.objects.all()
    municipalities = Municipality.objects.all()
    context = {
        'regions': regions,
        'municipalities': municipalities,
    }
    return render(request, 'municipalities/index.html', context)


def detail_municipalities(request, m_id):
    municipality = get_object_or_404(Municipality, pk=m_id)
    context = {'municipality': municipality}
    return render(request, 'municipalities/detail.html', context)


def detail_regions(request, r_id):
    region = get_object_or_404(Region, pk=r_id)
    context = {'region': region}
    return render(request, 'municipalities/detail.html', context)


def add_municipality(request):
    if request.method == "GET":
        return render(request, 'municipalities/add_municipality.html', {})
    elif request.method == "POST":
        m_code = int(request.POST['municipality_code'])
        m_name = request.POST['municipality_name']
        m_state = request.POST['stateRadio']
        m = Municipality(code=m_code, name=m_name, state=m_state)
        m.save()
        return HttpResponseRedirect(reverse('municipalities:index'))


def edit_municipality(request, m_id):
    municipality = get_object_or_404(Municipality, pk=m_id)
    if request.method == "GET":
        context = {'municipality': municipality}
        return render(request, 'municipalities/edit_municipality.html', context)
    elif request.method == "POST":
        if 'municipality_name' in request.POST:
            if request.POST['municipality_name'] != "":
                municipality.name = request.POST['municipality_name']
        municipality.state = request.POST['stateRadio']
        if municipality.state == 'U':
            for i in Region.objects.all():
                for j in i.municipalities.all():
                    if j.code == municipality.code:
                        i.municipalities.remove(municipality)
        municipality.save()
        return HttpResponseRedirect(reverse('municipalities:index'))


def delete_municipality(request, m_id):
    if request.method == "POST":
        m = get_object_or_404(Municipality, pk=m_id)
        m.delete()
    return HttpResponseRedirect(reverse('municipalities:index'))


def edit_region(request, r_id):
    region = get_object_or_404(Region, pk=r_id)
    municipalities = Municipality.objects.all()
    if request.method == "GET":
        context = {'region': region, 'municipalities': municipalities}
        return render(request, 'municipalities/edit_region.html', context)
    elif request.method == "POST":
        if 'region_name' in request.POST:
            if request.POST['region_name'] != "":
                region.name = request.POST['municipality_name']
        if request.POST.getlist('municipalitiesSelect'):
            for i in request.POST.getlist('municipalitiesSelect'):
                municipality = get_object_or_404(Municipality, pk=i)
                m = MunicipalityXRegion(municipality=municipality, region=region)
                m.save()
        if request.POST.getlist('deleteMunicipalitiesSelect'):
            for i in request.POST.getlist('deleteMunicipalitiesSelect'):
                municipality = get_object_or_404(Municipality, pk=i)
                region.municipalities.remove(municipality)
        region.save()
        return HttpResponseRedirect(reverse('municipalities:index'))


def delete_region(request, r_id):
    if request.method == "POST":
        r = get_object_or_404(Region, pk=r_id)
        r.delete()
    return HttpResponseRedirect(reverse('municipalities:index'))


def add_region(request):
    if request.method == "GET":
        m = Municipality.objects.all()
        return render(request, 'municipalities/add_region.html', {'municipalities': m})
    elif request.method == "POST":
        r_code = int(request.POST['region_code'])
        r_name = request.POST['region_name']
        r = Region(code=r_code, name=r_name)
        r.save()
        for i in request.POST.getlist('municipalitiesSelect'):
            municipality = get_object_or_404(Municipality, pk=i)
            m = MunicipalityXRegion(municipality=municipality, region=r)
            m.save()
        return HttpResponseRedirect(reverse('municipalities:index'))


regions/municipalities/templates/municipalities/add_municipality.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Regions</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
          <span class="navbar-brand mb-0 h1">Municipality Information</span>
    </nav>
<br>
<br>
<form action="{% url 'municipalities:add_municipality' %}" method="post">
{% csrf_token %}
  <div class="form-group row">
    <label for="municipality_code" class="col-sm-2 col-form-label"><b>Municipality Code:</b></label>
    <div class="col-sm-10">
      <input type="number" class="form-control" name="municipality_code" id="municipality_code" placeholder="Enter municipality code" required>
    </div>
  </div>
  <div class="form-group row">
    <label for="municipality_name" class="col-sm-2 col-form-label"><b>Municipality Name:</b></label>
    <div class="col-sm-10">
      <input type="text" class="form-control" name="municipality_name" id="municipality_name" placeholder="Enter municipality name" required>
    </div>
  </div>
  <fieldset class="form-group">
    <div class="row">
      <legend class="col-form-label col-sm-2 pt-0"><b>Municipality State:</b></legend>
      <div class="col-sm-10">
        <div class="form-check">
          <input class="form-check-input" type="radio" name="stateRadio" id="active" value="A" checked>
          <label class="form-check-label" for="active">
            Active
          </label>
        </div>
        <div class="form-check disabled">
          <input class="form-check-input" type="radio" name="stateRadio" id="unactive" value="U">
          <label class="form-check-label" for="unactive" style="color: #6c757d;">
            Unactive
          </label>
        </div>
      </div>
    </div>
  </fieldset>
  <div class="form-group row">
    <div class="col-sm-10">
      <input type="submit" value="Save" class="btn btn-primary">
    </div>
  </div>
</form>
</body>
</html>

regions/municipalities/templates/municipalities/add_region.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Regions</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
          <span class="navbar-brand mb-0 h1">Region Information</span>
    </nav>
<br>
<br>
<form action="{% url 'municipalities:add_region' %}" method="post">
{% csrf_token %}
  <div class="form-group row">
      <label for="region_code" class="col-sm-2 col-form-label"><b>Region Code:</b></label>
    <div class="col-sm-10">
      <input type="number" class="form-control" name="region_code" id="region_code" placeholder="Enter region code" required>
    </div>
  </div>
  <div class="form-group row">
      <label for="region_name" class="col-sm-2 col-form-label"><b>Region Name:</b></label>
    <div class="col-sm-10">
      <input type="text" class="form-control" name="region_name" id="region_name" placeholder="Enter region name" required>
    </div>
  </div>
  <div class="form-group">
    <label for="municipalitiesSelect"><b>Add Municipalities: </b></label>
    <select multiple="multiple" class="form-control" id="municipalitiesSelect" name="municipalitiesSelect">
        {% for m in municipalities %}
            {% if m.state != 'U' %}
                <option value="{{ m.code }}">{{ m.name }}</option>
            {% endif %}
        {% endfor %}
    </select>
    <small id="municipalitiesSelectHelp" class="form-text text-muted">Please use "Shift-Click" or "Cmd-Click" for more than one value</small>
  </div>
  <div class="form-group row">
    <div class="col-sm-10">
      <input type="submit" value="Save" class="btn btn-primary">
    </div>
  </div>
</form>
</body>
</html>

regions/municipalities/templates/municipalities/detail.html
 <!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Regions</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
          <span class="navbar-brand mb-0 h1">
              {% if municipality %}
                Municipality Information
              {% elif region %}
                Region Information
              {% endif %}
          </span>
    </nav>
    <br>
    <br>
    {% if municipality %}
        <dl class="row">
          <dt class="col-sm-3">Municipality name:<dt>
          <dd class="col-sm-9">{{ municipality.name }}</dd>

          <dt class="col-sm-3">Municipality state</dt>
          <dd class="col-sm-9">{{ municipality.get_state_display }}</dd>
        </dl>
         <div class="btn-group" role="group" aria-label="Options">
             <a href="{% url 'municipalities:edit_municipality' municipality.code %}" class="btn btn-dark" style="background-color: #343a40;">
                Edit
             </a>
             <form action="{% url 'municipalities:delete_municipality' municipality.code %}" method="post">
                 {% csrf_token %}
                 <input type="submit" value="Delete" class="btn btn-dark" style="background-color: #343a40;">
             </form>

         </div>
    {% elif region %}
        <dl class="row">
          <dt class="col-sm-3">Region name:<dt>
          <dd class="col-sm-9">{{ region.name }}</dd>

          <dt class="col-sm-3">Region Municipalities:<dt>
          <dd class="col-sm-9">
            {% if region.municipalities.all %}
                <ul>
                {% for m in region.municipalities.all %}
                    <li>{{ m.name }}</li>
                {% endfor %}
                </ul>
            {% else %}
                <p>No municipalities are available in this region.</p>
            {% endif %}
          </dd>
        </dl>

        <div class="btn-group" role="group" aria-label="Options">
             <a href="{% url 'municipalities:edit_region' region.code %}" class="btn btn-dark" style="background-color: #343a40;">
                Edit
             </a>
             <form action="{% url 'municipalities:delete_region' region.code %}" method="post">
                 {% csrf_token %}
                 <input type="submit" value="Delete" class="btn btn-dark" style="background-color: #343a40;">
             </form>
        </div>
    {% endif %}
</body>

regions/municipalities/templates/municipalities/edit_municipality.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Regions</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <span class="navbar-brand mb-0 h1">Municipality Information</span>
    </nav>
<br>
<br>
<form action="{% url 'municipalities:edit_municipality' municipality.code %}" method="post">
{% csrf_token %}
  <div class="form-group row">
    <label for="municipality_name" class="col-sm-2 col-form-label"><b>Municipality Name:</b></label>
    <div class="col-sm-10">
      <input type="text" class="form-control" name="municipality_name" id="municipality_name" placeholder="{{municipality.name}}">
    </div>
  </div>
  <fieldset class="form-group">
    <div class="row">
      <legend class="col-form-label col-sm-2 pt-0"><b>Municipality State:</b></legend>
      <div class="col-sm-10">
        <div class="form-check">
          <input class="form-check-input" type="radio" name="stateRadio" id="active" value="A" checked>
          <label class="form-check-label" for="active">
            Active
          </label>
        </div>
        <div class="form-check disabled">
          <input class="form-check-input" type="radio" name="stateRadio" id="unactive" value="U">
          <label class="form-check-label" for="unactive" style="color: #6c757d;">
            Unactive
          </label>
        </div>
      </div>
    </div>
  </fieldset>
  <div class="form-group row">
    <div class="col-sm-10">
      <input type="submit" value="Edit" class="btn btn-primary">
    </div>
  </div>
</body>
</html>

regions/municipalities/templates/municipalities/edit_region.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.min.js"></script>
    <meta charset="UTF-8">
    <title>Regions</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <span class="navbar-brand mb-0 h1">Region Information</span>
    </nav>
<br>
<br>
<form action="{% url 'municipalities:edit_region' region.code %}" method="post">
{% csrf_token %}
  <div class="form-group row">
      <label for="region_name" class="col-sm-2 col-form-label"><b>Region Name: </b></label>
    <div class="col-sm-10">
      <input type="text" class="form-control" name="region_name" id="region_name" placeholder="{{region.name}}">
    </div>
  </div>
  <div class="form-group">
    <label for="municipalitiesSelect"><b>Add Municipalities: </b></label>
    <select multiple="multiple" class="form-control" id="municipalitiesSelect" name="municipalitiesSelect">
        {% for m in municipalities %}
            {% if m.state != 'U' %}
                <option value="{{ m.code }}">{{ m.name }}</option>
            {% endif %}
        {% endfor %}
    </select>
    <small id="municipalitiesSelectHelp" class="form-text text-muted">Please use "Shift-Click" or "Cmd-Click" for more than one value</small>
  </div>
    {% if region.municipalities.all %}
        <div class="form-group">
            <label for="municipalitiesSelect"><b>Delete Municipalities: </b></label>
            <select multiple="multiple" class="form-control" id="deleteMunicipalitiesSelect" name="deleteMunicipalitiesSelect">
                {% for m in region.municipalities.all %}
                <option value="{{ m.code }}">{{ m.name }}</option>
                {% endfor %}
            </select>
            <small id="dmunicipalitiesSelectHelp" class="form-text text-muted">Please use "Shift-Click" or "Cmd-Click" for more than one value</small>
        </div>
    {% endif %}
  <div class="form-group row">
    <div class="col-sm-10">
      <input type="submit" value="Edit" class="btn btn-primary">
    </div>
  </div>
</form>
</body>
</html>

regions/municipalities/templates/municipalities/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Regions</title>
</head>
<body>
    <nav class="navbar sticky-top navbar-dark bg-dark">
      <span class="navbar-brand mb-0 h1">My World</span>
    </nav>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <div class="container">
      <div class="row">
        <div class="col-sm">
          <h1>Regions</h1>
            {% if regions %}

                {% for r in regions %}
                     <div class="list-group">
                          <a href="{% url 'municipalities:detail_regions' r.code %}" class="list-group-item list-group-item-action list-group-item-primary">
                            {{ r.name }}
                          </a>
                     </div>
                {% endfor %}

            {% else %}
                <p>No Regions are available.</p>
            {% endif %}
            <br>
            <br>
            <a href="{% url 'municipalities:add_region' %}" class="btn btn-dark" style="background-color: #343a40;">
                Add Region
            </a>
        </div>
        <div class="col-sm">
          <h1>Municipalities</h1>
            {% if municipalities %}

                {% for m in municipalities %}
                    <div class="list-group">
                          <a href="{% url 'municipalities:detail_municipalities' m.code %}" class="list-group-item list-group-item-action list-group-item-primary">
                            {{ m.name }}
                          </a>
                     </div>
                {% endfor %}
            {% else %}
                <p>No municipalities are available.</p>
            {% endif %}
            <br>
            <br>
            <a href="{% url 'municipalities:add_municipality' %}" class="btn btn-dark" style="background-color: #343a40;">
                Add Municipality
            </a>
        </div>
      </div>
    </div>

</body>
</html>